import time
time.sleep(5)
print("para ser directo")
time.sleep(1.4)
print("no me arrepiento")
time.sleep(1.7)
print("cosas de la vida")
time.sleep(1.5)
print("o de la mía")
time.sleep(2)
print("tu fuiste un momento")
time.sleep(2.3)
print("y te agradezco")
time.sleep(2)
print("pero no eras mía")
time.sleep(1.7)
print("y lo sabías")
time.sleep(2)
print("no fue mucho tiempo")
time.sleep(1.7)
print("y eso lo acepto")
time.sleep(1.7)
print("pero creía")
time.sleep(1.7)
print("lo que sentía")
time.sleep(2)
print("no respondías")
time.sleep(1.5)
print("y me moría")
time.sleep(2)
print("tu me tenías")
time.sleep(1.5)
print("y lo sabías")
time.sleep(1.7)
print("yo")
time.sleep(0.6)
print("no")
time.sleep(0.6)
print("soy")
time.sleep(0.6)
print("aquel")
time.sleep(0.6)
print("que te dió rosas")
time.sleep(2)
print("pero te dí mi corazón")
time.sleep(2)
print("y es más valiosa")
time.sleep(2.3)
print("la forma en que te trataba")
time.sleep(2)
print("y lo superé")
time.sleep(3.1)
print("la")
time.sleep(0.3)
print("canción")
time.sleep(0.6)
print("se acaba")
time.sleep(1.3)
print("y tu constante")
time.sleep(2)
print("el whatsapp me lo estás llenando de mensajes")
time.sleep(2.6)
print("hey, ya no me llames")
time.sleep(1.5)
print("que el amor también se volvió odio")
time.sleep(2.4)
print("recordé")
time.sleep(27)




print("no fue mucho tiempo")
time.sleep(1.7)
print("y eso lo acepto")
time.sleep(1.7)
print("pero creía")
time.sleep(1.7)
print("lo que sentía")
time.sleep(2)
print("no respondías")
time.sleep(1.5)
print("y me moría")
time.sleep(2)
print("tu me tenías")
time.sleep(1.5)
print("y lo sabías")
time.sleep(1.7)
print("yo")
time.sleep(0.6)
print("no")
time.sleep(0.6)
print("soy")
time.sleep(0.6)
print("aquel")
time.sleep(0.6)
print("que te dió rosas")
time.sleep(2)
print("pero te dí mi corazón")
time.sleep(2)
print("y es más valiosa")
time.sleep(2.3)
print("la forma en que te trataba")
time.sleep(2)
print("y lo superé")
time.sleep(3.1)
print("la")
time.sleep(0.3)
print("canción")
time.sleep(0.6)
print("se acaba")
time.sleep(1.3)
print("y tu constante")
time.sleep(2)
print("el whatsapp me lo estás llenando de mensajes")
time.sleep(2.6)
print("hey, ya no me llames")
time.sleep(1.5)
print("que el amor también se volvió odio")
time.sleep(2.4)
print("recordé")
time.sleep(4)